project_id = "bmrifufykczudfxomenr"

[edge_functions.ai-chat]
verify_jwt = true

[edge_functions.realtime-chat]
verify_jwt = false

[edge_functions.text-to-speech]
verify_jwt = false

[edge_functions.speech-to-text]
verify_jwt = false

[edge_functions.send-invitation]
verify_jwt = true

[edge_functions.accept-invitation]
verify_jwt = false

[edge_functions.complete-invitation]
verify_jwt = true

[edge_functions.session-analysis]
verify_jwt = true

[edge_functions.invite-manager]
verify_jwt = true

[edge_functions.leave-team]
verify_jwt = true

[edge_functions.remove-team-member]
verify_jwt = true

[edge_functions.auth-emails]
verify_jwt = false

[edge_functions.test-chat]
verify_jwt = false